### ISSUE TITLE
Allow multiple branches in push(), pull(), fetch()

### ISSUE THREAD

**Issue by lehni** [stevelacy/gulp-git#108]
Git allows multiple `<refspec>` arguments in these calls, e.g.:

https://git-scm.com/docs/git-pull

It would be nice if `gulp-git` reflected that an allowed the current `branch` parameter to optionally receive an array instead of string, and handled that accordingly.

**Comment by stevelacy** [comment]
PR?

**Comment by lehni** [comment]
I can give it a go. Wanted to see first if you'd accept it.

**Comment by nfantone** [comment]
Also, I'd like to add that something like this:

```javascript
git.push('origin', 'develop master', { quiet: true }, done);
```

Does _not_ work.

```
[15:18:51] Error: Command failed: git push origin 'develop master' --tags
fatal: remote part of refspec is not a valid name in develop master

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:484:12)
```

But you can still push all your branches using `*:*`.

**Comment by stevelacy** [comment]
The branch is _not_ a valid git command.

**Comment by nfantone** [comment]
Clearly. That's the whole point of this issue.

PR coming in a second, @stevelacy.

**Comment by nfantone** [comment]
Here: https://github.com/stevelacy/gulp-git/pull/123

**Comment by stevelacy** [comment]
Ty @nfantone
