### ISSUE TITLE
Sample commit task does not work

### ISSUE THREAD

**Issue by nfantone** [stevelacy/gulp-git#117]
The simplest `git commit` example on the docs just fails showing git's help message.

This,

```javascript
gulp.task('commit', function(){
  return gulp.src('./*')
    .pipe(git.commit('initial commit'));
});
```

Ends up with:

```sh
[12:37:33] Starting 'commit'...
[12:37:33] 'commit' errored after 27 ms
[12:37:33] Error: Command failed: /bin/sh -c git commit -m "initial commit"   'package.json'

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:475:12)
```

I can see that the arguments sent to `/bin/sh` are not quoted. In fact, running the command manually fails, indeed.

```sh
$  /bin/sh -c git commit -m "initial commit"   'package.json'
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
...

$ echo $?
1
```

But if you properly quote the command, it works as expected:

```sh
$ /bin/sh -c "git commit -m 'initial commit'   'package.json'"
On branch develop
Changes not staged for commit:
	modified:   gulpfile.js

no changes added to commit
```

**Comment by nfantone** [comment]
@stevelacy Tested on, 
-  git `1.9.1` on Ubuntu 14.04
- git `2.8.1` on Mint 17.3

Same result.
