### ISSUE TITLE
Tag without message

### ISSUE THREAD

**Issue by maybeec** [stevelacy/gulp-git#139]
Although, the [documentation](https://www.npmjs.com/package/gulp-git#gittagversion-message-opt-cb) says, that the git tag message is optional, leaving out the message like this

```js
  git.tag('v' + pjson.version, function (err) {
    if (err) throw err;
    done();
  });
```
results in 

```
Message:
    path.replace is not a function
Stack:
TypeError: path.replace is not a function
    at escapePathWin (XXX\node_modules\any-shell-escape\shell-escape.js:14:23)
    at XXX\node_modules\any-shell-escape\shell-escape.js:32:16
    at Array.forEach (native)
    at module.exports (XXX\node_modules\any-shell-escape\shell-escape.js:31:19)
    at Object.module.exports [as tag] (XXX\node_modules\gulp-git\lib\tag.js:19:50)
    at Gulp.<anonymous> (XXX\gulpfile.js:150:7)
    at module.exports (XXX\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (XXX\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (XXX\node_modules\orchestrator\index.js:214:10)
    at XXX\node_modules\orchestrator\index.js:279:18
```

**Comment by stevelacy** [comment]
```js
 git.tag('v' + pjson.version, '', function (err) {
    if (err) throw err;
    done();
  });


```

**Comment by maybeec** [comment]
This is basically not the same. It creates an annotated tag with an empty string.
What I propose is an optional parameter to allow creating lightweight git tags: https://git-scm.com/book/en/v2/Git-Basics-Tagging#Lightweight-Tags

**Comment by stevelacy** [comment]
PR?

**Comment by stevelacy** [comment]
Want me to jump on this? Does it make sense to have a `lightweight: true` option passed instead of just a null message?

**Comment by stevelacy** [comment]
How does this look: https://github.com/stevelacy/gulp-git/commit/96f9a9af3dfc7136545062ebdf3adfa64c6a3668

**Comment by maybeec** [comment]
Looks good. Thanks... unfortunately I lost sight of this issue.
Thanks for fixing!

**Comment by stevelacy** [comment]
All right, I will publish

**Comment by stevelacy** [comment]
https://github.com/stevelacy/gulp-git/releases/tag/1.13.0
