### ISSUE TITLE
where can I configure the username and password when I use push method?

### ISSUE THREAD

**Issue by stephenliu1944** [stevelacy/gulp-git#142]
[00:09:38] Using gulpfile D:\Lab\Frontend\gulp\git-test\gulpfile.js
[00:09:38] Starting 'add'...
[00:09:39]
[00:09:39] Finished 'add' after 144 ms
[00:09:39] Starting 'commit'...
[00:09:39] [master 69d3842] initial commit
 1 file changed, 2 insertions(+), 2 deletions(-)

[00:09:39] Finished 'commit' after 124 ms
[00:09:39] Starting 'push'...
[00:09:39] Finished 'push' after 3.75 ms
[00:09:39] Starting 'default'...
[00:09:39] Finished 'default' after 19 μs
D:\Lab\Frontend\gulp\git-test\gulpfile.js:16
        if (err) throw err;
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument
    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by stevelacy** [comment]
It is the same way as using git usually.

This is your error:
```
D:\Lab\Frontend\gulp\git-test\gulpfile.js:16
if (err) throw err;
bash: /dev/tty: No such device or address
```
You are on windows, that command is a linux command. What are you running that triggers that error?

**Comment by stephen1944** [comment]
```
gulp.task('push', ["add", "commit"], function(){
    git.push('origin', 'master', {cwd: './git-test/'}, function (err) {
        if (err) console.log(err);
    });
});``
```
I use https method to push  code to git, so I need to enter username and password, is there a way to configure them?

**Comment by stevelacy** [comment]
This plugin does not support passing username/password through, It does support using credentials saved in your git credential store: http://stackoverflow.com/questions/5343068/is-there-a-way-to-skip-password-typing-when-using-https-on-github, or (best) use ssh https://help.github.com/articles/connecting-to-github-with-ssh/
