### ISSUE TITLE
Unable to use git clone over ssh on Windows

### ISSUE THREAD

**Issue by martinambrus** [stevelacy/gulp-git#155]
Hi,

I'm on Windows 7, and running gulp.clone does not get piped through the terminal to ask for password for the id_rsa key. It automatically goes to error:

```
Could not clone from git! Exitting...  { Error: Command failed: git clone "git@************/docker.kafka.git"
Cloning into 'docker.kafka'...
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 128,
  signal: null,
  cmd: 'git clone "git@*****************/docker.kafka.git"  ' }
```

When I try an ordinary git clone via terminal (any command-line, the built-in one, PowerShell or even Cmder), everything works as expected. I even tried explicitly adding `config` file into my `~/.ssh` folder, which yields the same results.

**Comment by martinambrus** [comment]
If the question was aimed at me, unfortunately I couldn't get this working. Instead, I've created a Linux dev environment via Docker where this works without problems.

**Comment by arunvishun** [comment]
Thanks for the response @martinambrus. I will update if i get some workaround.

**Comment by martinambrus** [comment]
@stevelacy has this been resolved, or a wontfix at the end?

**Comment by stevelacy** [comment]
Almost a year without a concise reason for the error from the community. I do not use windows, thus I can't duplicate. The error is not on this project's end, and would be a configuration with powershell or windows.

**Comment by martinambrus** [comment]
Thanks for the answer. Just to clarify once again, I did try this both, inside and outside of PoweShell (i.e. using the ordinary command-line, cmder, cygwin), so while it might not be this project's fault, it's definitely not a PowerShell configuration issue.

**Comment by stevelacy** [comment]
is there a way to do `ssh-add` on windows?

**Comment by stevelacy** [comment]
I am wondering if node is spawning the process without access to the ssh-agent

**Comment by martinambrus** [comment]
There is no ssh agent on windows, nor is there a native ssh-add.
