### ISSUE TITLE
git.tag() returns an error instead of a list of tags.

### ISSUE THREAD

**Issue by Maleki** [stevelacy/gulp-git#170]
**gulp-git version**: 2.4.1

Documentation states that when no arguments are used all tags are returned. [link](https://github.com/stevelacy/gulp-git#gittagversion-message-opt-cb)

**Demo code**:
```
var gulp = require('gulp');
var git = require('gulp-git');

gulp.task('tagtest', function(){
    var a = git.tag();
});
```

**Expected**:  List of tags.

**Actual Results**: Error below: 
```
Error: Failed to provide the current file as "file" to the template
    at wrapped (S:\Storage\Projects\ci-test-1\node_modules\gulp-util\lib\template.js:17:13)
    at Object.module.exports [as template] (S:\Storage\Projects\ci-test-1\node_modules\gulp-util\lib\template.js:22:18)
    at Object.module.exports [as tag] (S:\Storage\Projects\ci-test-1\node_modules\gulp-git\lib\tag.js:35:21)
    at Gulp.<anonymous> (S:\Storage\Projects\ci-test-1\gulpfile.js:19:17)
    at module.exports (S:\Storage\Projects\ci-test-1\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (S:\Storage\Projects\ci-test-1\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (S:\Storage\Projects\ci-test-1\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (S:\Storage\Projects\ci-test-1\node_modules\orchestrator\index.js:134:8)
    at C:\Users\someguy\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:51:20
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

```

**Comment by stevelacy** [comment]
Fixed, sorry about that, publishing shortly
