### ISSUE TITLE
using git.exec subcommands 

### ISSUE THREAD

**Issue by xetra11** [stevelacy/gulp-git#171]
I tried the following:

` git.exec({args: 'log $(git describe --tags --abbrev=0)..HEAD) --pretty=format:\\"%s\\",'}`...

But following error message appeared:

```

   if (err) throw err;
             ^

Error: Command failed: git log $(git describe --tags --abbrev=0)..HEAD) --pretty=format:\"%s\",
fatal: ambiguous argument '`git': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:484:12)
```

**Comment by stevelacy** [comment]
The command seems to be missing a closing bracket, did you verify that it works as is in bash?

**Comment by xetra11** [comment]
yea testeed it in bash...
will check that bracked issue

**Comment by stevelacy** [comment]
I ran the command as:
```
gulp.task('log', function () {
  git.exec({args: 'log $(git describe --tags --abbrev=0)..HEAD) --pretty=format:\\"%s\\",'})
})

```
And it did not throw any errors. It did not log anything either.
