### ISSUE TITLE
gulp-git breaks in Node 9.5.0.

### ISSUE THREAD

**Issue by pford68** [stevelacy/gulp-git#179]
The issue appears to be require-dir dependency.  The latter appears to be a known issue in Node v8 and up, and it seems to affect several modules that use require-dir.

```
TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/Users/paford/Projects/D-F/mjs-microservices/node_modules/gulp-git/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/Users/paford/Projects/D-F/mjs-microservices/node_modules/gulp-git/index.js:4:18)
```

**Comment by stevelacy** [comment]
Does require-dir 1.0.0 fix this if you know?
require-dir build is passing just fine on 9.5.0: https://travis-ci.org/aseemk/requireDir/jobs/338757106

**Comment by pford68** [comment]
@stevelacy Yes, it appears that 1.0.0 does fix it.

**Comment by stevelacy** [comment]
Sounds good, I'll update the dependency.
