### ISSUE TITLE
stdout maxBuffer length exceeded (diff.js)

### ISSUE THREAD

**Issue by Pavel311** [stevelacy/gulp-git#192]
I ran into a error while comparing two branches with large amount of changes.

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at Socket.onChildStdout (child_process.js:348:14)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:261:13)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
Emitted 'error' event at:
    at /home/user/git/projectname/node_modules/gulp-git/lib/diff.js:87:31
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:600:12)
```

I found similar problem with solution [issue#68](https://github.com/stevelacy/gulp-git/issues/68#issuecomment-293214116).

In [diff.js:86](https://github.com/stevelacy/gulp-git/blob/master/lib/diff.js#L86) I changed
```
exec('git diff --raw -z ' + cmd, {cwd: opt.cwd}, function(err, stdout) {
```

to
```
exec('git diff --raw -z ' + cmd, {cwd: opt.cwd, maxBuffer: Infinity}, function(err, stdout) {
```

Now everything works.

**Comment by stevelacy** [comment]
Added option to pass it in, thanks for reporting
