### ISSUE TITLE
Nested commands

### ISSUE THREAD

**Issue by MrHen** [stevelacy/gulp-git#92]
Is there a way for me to execute this command:

```
git push heroku `git subtree split --prefix server master`:master --force
```

I tried:

```
gulp.task('deploy:heroku', ['build:server', 'test:run'], function() {
    gulp_git.push('heroku', '`git subtree split --prefix server master`:master', {args: " --force"}, function (err) {
        if (err) throw err;
    });
});
```

And saw this output:

```
/Users/adambabcock/Source/obtuse-octo-adventure/server/gulpfile.js:178
        if (err) throw err;
                       ^
Error: Command failed: error: src refspec `git subtree split --prefix server master` does not match any.
error: failed to push some refs to 'https://git.heroku.com/murmuring-tundra-3318.git'

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by stevelacy** [comment]
Try this

```js

gulp.task('deploy:heroku', ['build:server', 'test:run'], function() {
    gulp_git.push('heroku', '$(git subtree split --prefix server master):master', {args: " --force"}, function (err) {
        if (err) throw err;
    });
});


```
