### ISSUE TITLE
Committing not working - OSX and Ubuntu

### ISSUE THREAD

**Issue by simonh1000** [stevelacy/gulp-git#96]
Trying this for the first time, so maybe I've done something wrong, but I'm getting this sort of final command and corresponding error. (I have to copy all my wordpress files into a rather weired folder structure so that it can be pushed to openshift)
```
Error: Command failed: /bin/sh -c git commit -m "update Fri Oct 02 2015 15:11:30 GMT+0200 (CEST)"   'README.md'
```
If I try to run the command directly, I get the whole help message back from git, as though none of the rest of the parameters have been read. It does work manually when I wrap the whole git command in `' '`
Am I doing something wrong? Using modern ubuntu and osx.
```
gulp.task('gitOShift', function() {
    var now = new Date();
    process.chdir('../openshift/');

    return gulp.src(['README.md'])
    .pipe(git.add())
    .pipe(git.commit('update ' + now))
    // /bin/sh -c 'git commit -m "update" "README.md"'
    // .pipe(git.push('origin', 'master', function (err) {
    //     if (err) throw err;
    // }));
});
```

**Comment by stevelacy** [comment]
Your git paths seem a bit odd, can you run `which git` and `git --version`.

**Comment by simonh1000** [comment]
/usr/bin/git
git version 2.1.4
I see that git is a bit old, but I think this came with ubuntu

**Comment by simonh1000** [comment]
I have a terrible feeling that the problem was due to me keeping on trying the commit code when there were no changes, and your code was getting a 'nothing to do' error code but not really passing it on.

**Comment by simonh1000** [comment]
But now I am getting this error from the commit line

```
/home/simon/code/af2015wp/wp-content/themes/af2015/node_modules/gulp-git/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623
    var written = dest.write(chunk);
                       ^

TypeError: dest.write is not a function
    at write (/home/simon/code/af2015wp/wp-content/themes/af2015/node_modules/gulp-git/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/simon/code/af2015wp/wp-content/themes/af2015/node_modules/gulp-git/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/home/simon/code/af2015wp/wp-content/themes/af2015/node_modules/gulp-git/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/home/simon/code/af2015wp/wp-content/themes/af2015/node_modules/gulp-git/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/home/simon/code/af2015wp/wp-content/themes/af2015/node_modules/gulp-git/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/home/simon/code/af2015wp/wp-content/themes/af2015/node_modules/gulp-git/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/home/simon/code/af2015wp/wp-content/themes/af2015/node_modules/gulp-git/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/home/simon/code/af2015wp/wp-content/themes/af2015/node_modules/gulp-git/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
```
Note that I am using Node 4.1.1.

**Comment by seiyria** [comment]
@simonh1000 I'm having this problem as well, did you manage to resolve it?

**Comment by simonh1000** [comment]
Yes, I hadn't read the instructions carefully enough!
I was using 
```
git.src('....')
.pipe(git.add())
.pipe(git.commit(...))
.pipe(git.push('origin', 'master',...)
```

I had to run git.push as a separate task that had no `git.src` to kick it off. Hope this helps you.

**Comment by seiyria** [comment]
Actually, my problem was that I had to run the push in a callback for commit - I couldn't run it as it's own function in pipe. All good now though! :D

**Comment by jahanzaibaslam-vteams** [comment]
@simonh1000 I have the same problem as @seiyria described.  I have to run the push in a callback for commit - I couldn't run it as it's own function in pipe. Please help to figure out how can i do this?

**Comment by stevelacy** [comment]
@jahanzaibaslam-vteams please read the docs: 
https://github.com/stevelacy/gulp-git#gitpushremote-branch-opt-cb
https://github.com/stevelacy/gulp-git#040-introduced-breaking-changes
https://github.com/stevelacy/gulp-git/blob/master/examples/gulpfile.js#L74
